/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import conexiones.conexionSQL;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Maza
 */
public class frmMiCRUD extends javax.swing.JFrame {
    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();

    /**
     * Creates new form frmMiCRUD
     */
    public frmMiCRUD() {
        initComponents();
        
        
        lblMensaje.setText("Constructor sin parametros");
    }
    
    public frmMiCRUD(String parametro1){
           initComponents();
           this.lblMensaje.setText(parametro1);
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        lblNOMBRE = new javax.swing.JLabel();
        txtNOMBREALUM = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtAPELLIDO = new javax.swing.JTextField();
        lblCURSO = new javax.swing.JLabel();
        txtCURSO = new javax.swing.JTextField();
        cmdGUARDAR = new javax.swing.JButton();
        cmdEDITAR = new javax.swing.JButton();
        cmdELIMINAR = new javax.swing.JButton();
        cmdNUEVO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCALIFICACION = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        Mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensaje.setText("PRUEBA CONSTRUCTOR");

        lblNOMBRE.setText("Nombre del Alumno");

        lblApellido.setText("Apellidos del Alumno:");

        txtAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPELLIDOActionPerformed(evt);
            }
        });

        lblCURSO.setText("Curso:");

        cmdGUARDAR.setText("GUARDAR");
        cmdGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGUARDARActionPerformed(evt);
            }
        });

        cmdEDITAR.setText("EDITAR");
        cmdEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEDITARActionPerformed(evt);
            }
        });

        cmdELIMINAR.setText("ELIMINAR");
        cmdELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdELIMINARActionPerformed(evt);
            }
        });

        cmdNUEVO.setText("NUEVO");
        cmdNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNUEVOActionPerformed(evt);
            }
        });

        jtablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaAlumnos);

        jLabel1.setText("Calificacion");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        Mostrar.setText("Mostrarr");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1)
                                            .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                            .addComponent(txtCURSO)
                                            .addComponent(lblCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAPELLIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                            .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCALIFICACION)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(Buscar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Mostrar))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(cmdGUARDAR)
                                                .addGap(27, 27, 27)
                                                .addComponent(cmdEDITAR)))
                                        .addGap(26, 26, 26)
                                        .addComponent(cmdELIMINAR)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmdNUEVO)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNOMBRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblCURSO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCALIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdGUARDAR)
                            .addComponent(cmdEDITAR)
                            .addComponent(cmdELIMINAR)
                            .addComponent(cmdNUEVO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buscar)
                            .addComponent(Mostrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(lblMensaje)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPELLIDOActionPerformed

    private void cmdGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGUARDARActionPerformed
        // TODO add your handling code here:
        insertarDatos();
       
    }//GEN-LAST:event_cmdGUARDARActionPerformed

    public void insertarDatos(){
        try{
            String SQL = "insert into EstudColegio (NombreEst,ApellidoEst,CursoEst,Calificacion) values(?,?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, txtNOMBREALUM.getText());
            pst.setString(2, txtAPELLIDO.getText());
            pst.setString(3, txtCURSO.getText());
            pst.setString(4, txtCALIFICACION.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro Exitoso");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al Registrar");
        }
    }
    private void cmdELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdELIMINARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdELIMINARActionPerformed

    private void cmdEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEDITARActionPerformed
        // TODO add your handling code here: 
   
        conexionSQL cc = new conexionSQL();
        Connection cn = cc.conexion();
        
        String snombre,sapellido,scurso,scalificacion,sSql;
        snombre = txtNOMBREALUM.getText();
        sapellido = txtAPELLIDO.getText();
        scurso = txtCURSO.getText();
        scalificacion = txtCALIFICACION.getText();
            
        sSql ="Update EstudColegio  set NombreEst=?,ApellidoEst=?,CursoEst=? where CalificacionAlum=?)";
        try{
            PreparedStatement p = cn.prepareStatement(sSql);
                
            p.setString(1, snombre);
            p.setString(2, sapellido);
            p.setString(3, scurso);
            p.setString(4,scalificacion);
            p.executeUpdate();
              
          JOptionPane.showMessageDialog(this,"si se actualizo");      
         txtAPELLIDO.setText("");
         txtCURSO.setText("");
         txtNOMBREALUM.setText("");
         txtNOMBREALUM.setEnabled(true);
               cmdEDITAR.setEnabled(true);
               txtAPELLIDO.setEnabled(true);
               txtCURSO.setEnabled(true);
               Buscar.setEnabled(true);
               
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"no se pudo");
        }            
   
    }//GEN-LAST:event_cmdEDITARActionPerformed

    private void cmdNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNUEVOActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_cmdNUEVOActionPerformed

    private void jtablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaAlumnosMouseClicked
        // TODO add your handling code here:
        int seleccion = jtablaAlumnos.rowAtPoint(evt.getPoint());
        
        txtNOMBREALUM.setText(jtablaAlumnos.getValueAt(seleccion, 1).toString());
        txtAPELLIDO.setText(jtablaAlumnos.getValueAt(seleccion, 2).toString());
        txtCURSO.setText(jtablaAlumnos.getValueAt(seleccion, 3).toString());
        txtCALIFICACION.setText(jtablaAlumnos.getValueAt(seleccion, 4).toString());
    }//GEN-LAST:event_jtablaAlumnosMouseClicked

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
               txtID.setEnabled(true);
               txtNOMBREALUM.setEnabled(true);
               txtAPELLIDO.setEnabled(true);
               txtCURSO.setEnabled(true);
               txtCALIFICACION.setEnabled(true);
               cmdELIMINAR.setEnabled(true);
               cmdGUARDAR.setEnabled(true);
               conexionSQL cc = new conexionSQL();
               Connection cn = cc.conexion();
               
               String sConsulta = "Select * from EstudColegio where idEst = '"+txtID.getText()+"';";
               try{
                   Statement consulta = cn.createStatement();
                   ResultSet rs = consulta.executeQuery(sConsulta);
                   rs.next();
                   String valor = rs.getString(1);
                   JOptionPane.showMessageDialog(this, valor);
                   txtID.setText(rs.getString(1));
                   txtNOMBREALUM.setText(rs.getString(2));
                   txtAPELLIDO.setText(rs.getString(3));
                   txtCURSO.setText(rs.getString(4));
                   txtCALIFICACION.setText(rs.getString(5));
                   cmdEDITAR.setEnabled(true);
                  }catch(SQLException ex){
                      JOptionPane.showMessageDialog(this,"no hay datos Guardados con ID ingresado");
                      txtAPELLIDO.setText("");
                      txtCURSO.setText("");
                      txtCALIFICACION.setText("");
                      cmdGUARDAR.setEnabled(true);
                  }
    
    }//GEN-LAST:event_BuscarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
       String[] titulos = {"ID","Nombre","Apellido", "Curso", "Calificacion"};
        
        String[] registros = new String[7];
        
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String sql = "select * from  EstudColegio";
        
        try{
        
        Statement  st = con.createStatement();
        ResultSet  rs = st.executeQuery(sql);
        
        while(rs.next()){
        
            registros[0] = rs.getString("idEst");
            registros[1] = rs.getString(("NombreEst"));
            registros[2] = rs.getString("ApellidoEst");
            registros[3] = rs.getString("CursoEst");
            registros[4] = rs.getString("Calificacion");
            
            modelo.addRow(registros);
        }
        
        jtablaAlumnos.setModel(modelo);
        
        } catch (Exception e)
        {
        JOptionPane.showMessageDialog(null, "Error al mostrar Datos" + e.getMessage());
        }
        
        
    }//GEN-LAST:event_MostrarActionPerformed

    public void limpiarDatos(){
    txtAPELLIDO.setText("");
    txtNOMBREALUM.setText("");
    txtCALIFICACION.setText("");
    txtCURSO.setText("");
    txtID.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMiCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton cmdEDITAR;
    private javax.swing.JButton cmdELIMINAR;
    private javax.swing.JButton cmdGUARDAR;
    private javax.swing.JButton cmdNUEVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jtablaAlumnos;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCURSO;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNOMBRE;
    private javax.swing.JTextField txtAPELLIDO;
    private javax.swing.JTextField txtCALIFICACION;
    private javax.swing.JTextField txtCURSO;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOMBREALUM;
    // End of variables declaration//GEN-END:variables
}


